// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ExcelExample.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("Calculator Multiply Feature", Description="\tIn order to avoid silly mistakes\r\n\tAs a math idiot\r\n\tI want to be told the produ" +
        "ct of two numbers", SourceFile="Features\\CalculatorMultiply.feature", SourceLine=0)]
    public partial class CalculatorMultiplyFeatureFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "CalculatorMultiply.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Calculator Multiply Feature", "\tIn order to avoid silly mistakes\r\n\tAs a math idiot\r\n\tI want to be told the produ" +
                    "ct of two numbers", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void AddTwoNumbers(string factorOne, string factorTwo, string result, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add two numbers", exampleTags);
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.Given(string.Format("I have entered {0} into the calculator", factorOne), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 8
 testRunner.And(string.Format("I have also entered {0} into the calculator", factorTwo), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 9
 testRunner.When("I press multiply", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 10
 testRunner.Then(string.Format("The result should be {0} on the screen", result), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add two numbers, -10", new string[] {
                "source:MultiplyTwoNumbers.part.examples.xlsx"}, SourceLine=14)]
        public virtual void AddTwoNumbers_10()
        {
            this.AddTwoNumbers("-10", "10", "-100", new string[] {
                        "source:MultiplyTwoNumbers.part.examples.xlsx"});
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add two numbers, 42", new string[] {
                "source:MultiplyTwoNumbers.part.examples.xlsx"}, SourceLine=14)]
        public virtual void AddTwoNumbers_42()
        {
            this.AddTwoNumbers("42", "13", "546", new string[] {
                        "source:MultiplyTwoNumbers.part.examples.xlsx"});
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add two numbers, 70", new string[] {
                "source:MultiplyTwoNumbers.part.examples.xlsx"}, SourceLine=14)]
        public virtual void AddTwoNumbers_70()
        {
            this.AddTwoNumbers("70", "50", "3500", new string[] {
                        "source:MultiplyTwoNumbers.part.examples.xlsx"});
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Add two numbers, 1", new string[] {
                "source:MultiplyTwoNumbers.part.examples.xlsx"}, SourceLine=14)]
        public virtual void AddTwoNumbers_1()
        {
            this.AddTwoNumbers("1", "2", "2", new string[] {
                        "source:MultiplyTwoNumbers.part.examples.xlsx"});
#line hidden
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
