# ------------------------------------------------------------------------------
#  <auto-generated>
#      This code was generated by SpecFlow+ Excel (http://www.specflow.org/plus/Excel).
#      SpecFlow Version:2.3.2.0
#      SpecFlow+ Excel Version:1.7.3.0
# 
#      Changes to this file may cause incorrect behavior and will be lost if
#      the code is regenerated.
#  </auto-generated>
# ------------------------------------------------------------------------------

Feature: Sample-ExcelFeature

Scenario: Add two numbers from Excel
	Given I have entered 50 into the calculator
	And I have entered 90 into the calculator
	When I press add
	Then the result should be 140 on the screen


Scenario Outline: Add two numbers from Excel (SO)
	Given I have entered <a> into the calculator
	And I have entered <b> into the calculator
	When I press add
	Then the result should be <result> on the screen

Examples: 
	| case    | a  | b  | result |
	| classic | 50 | 70 | 120    |
	| simple  | 2  | 3  | 5      |


