// <auto-generated />
namespace DAL.EF.Migrations.Conventions
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Finale : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Finale));
        
        string IMigrationMetadata.Id
        {
            get { return "201608101617252_Finale"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
